### ISSUE TITLE
wrong export in index.js

### ISSUE THREAD

**Issue by harouny** [krakenjs/cross-domain-utils#1]
```./index.js``` (package main) has the following export, which I think has the wrong file since ```dist``` doesn't have ```smorgarsbord```:
``` javascript
module.exports = require('./dist/smorgarsbord');
```

Maybe the right export  can be:
``` javascript
module.exports = require('./src');
```

**Comment by harouny** [comment]
Hey @bluepnume 
Just a tag in case no one is following this one.

**Comment by bluepnume** [comment]
Erk. Good catch. I'll make a fix shortly.

**Comment by bluepnume** [comment]
Fixed.
