### ISSUE TITLE
Create TypeScript typings

### ISSUE THREAD

**Issue by mstuart** [krakenjs/cross-domain-utils#11]
This project isn't written in TypeScript, but many TypeScript users would like to use published typings. For this issue, create TypeScript typings that cover the exported functions, and contribute it back to DefinitelyTyped!

This issue is great for someone who wants to learn more about TypeScript!

**Comment by ShoeBoom** [comment]
I would like to work on this

**Comment by ANovokmet** [comment]
I've made  [ANovokmet/DefinitelyTyped#cross-domain-utils-types](https://github.com/ANovokmet/DefinitelyTyped/commit/25340393cdb05672dd5c1cd7dd75d62529798b18).
Should function argument types use the `CrossDomainWindowType` interface or `Window` (from `lib.dom.d.ts`)? Not sure about this.

**Comment by ShoeBoom** [comment]
Looks like @ANovokmet has already started. I'm going to leave it be this time, but you should say you want to work on something before you start.

This way you don't make other people waste their time.

**Comment by ANovokmet** [comment]
@ShoeBoom sorry, will do! This is my first time contributing to github open source, so I'm only aware of the guides on the Hacktoberfest page, and there is much. I might have glanced over the part where you have to claim the issue, which does make sense.

**Comment by ANovokmet** [comment]
Types were merged with DefinitelyTyped/DefinitelyTyped#48470. 

https://www.npmjs.com/package/@types/cross-domain-utils

**Comment by mstuart** [comment]
Thanks!
