### ISSUE TITLE
Postinstall script 'flow-typed install'

### ISSUE THREAD

**Issue by PlexusMark** [krakenjs/cross-domain-utils#7]
As of version 2.0.2 the build process is failing at the postinstall script:

`npm ERR! Failed at the cross-domain-utils@2.0.2 postinstall script 'flow-typed install'.`

This is new to version 2.0.2 and does not occur on 2.0.1.

**Comment by ming-codes** [comment]
Yup, getting this too.

[This line](https://github.com/krakenjs/cross-domain-utils/blob/master/package.json#L19)

**Comment by bluepnume** [comment]
Guh, good catch. I'm removing this post-install step for now and re-publishing.

**Comment by bluepnume** [comment]
OK published, please let me know if you still see this problem. Thanks!

**Comment by PlexusMark** [comment]
Build worked this time, thank you!
